spring.application.name=Jvaweb

# Connexion à PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/gestion_client
spring.datasource.username=postgres
spring.datasource.password=1234

# Timeouts pour la connexion (évite le blocage)
spring.datasource.hikari.initialization-fail-timeout=60000
spring.datasource.hikari.connection-timeout=30000

# Désactiver la création automatique des tables au démarrage
spring.jpa.hibernate.ddl-auto=none

# Permettre à l'application de démarrer même sans base de données
spring.jpa.defer-datasource-initialization=true

# Configuration JPA
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Désactiver le cache Thymeleaf pour le développement
spring.thymeleaf.cache=false